info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

security:
  user:
    name: admin
    password: admin

quartz:
  threadCount: 15

mail:
  to: test@test.com,test2@test.com,test3@test.com
  host: smtp.gmail.com
  port: 587
  username: test.test@gmail.com
  password: test
  smtp:
   startTls:
    enable: true
    required: true
   auth: true

  
---

quartz:
  jobstore:
    clustered: false

spring:
  profiles: mysql-jobstore
  datasource:
    url: "jdbc:mysql://mysql/onyx"
    username: onyx
    password: onyx